version: '3.8'

services:
  db-postgres:
    image: postgres:15-alpine
    container_name: polla-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Asdf123.}
      POSTGRES_DB: polla_mundialista
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d polla_mundialista"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: polla-backend
    environment:
      # Sobrescribimos el host local por el nombre del servicio de la DB
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD:-Asdf123.}@db-postgres:5432/polla_mundialista?schema=public
      PORT: 3000
      NODE_ENV: production
      FRONTEND_URL: http://localhost:4200
      JWT_ACCESS_SECRET: "p0lla-mund1al1sta-acc3ss-s3cr3t-k3y-2026"
      JWT_REFRESH_SECRET: "p0lla-mund1al1sta-r3fr3sh-s3cr3t-k3y-2026"
    ports:
      - "3000:3000"
    depends_on:
      db-postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: polla-frontend
    ports:
      - "4200:80" # Nginx expone el 80, lo mapeamos al 4200 para mantener tu URL actual
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
